"""create tables and relationships

Revision ID: 34961b814fc6
Revises: 
Create Date: 2021-08-03 07:56:17.500405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34961b814fc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('crs_id', sa.Integer(), nullable=False),
    sa.Column('crs_code', sa.String(length=20), nullable=False),
    sa.Column('crs_title', sa.String(length=50), nullable=False),
    sa.Column('crs_desc', sa.String(length=255), nullable=False),
    sa.Column('crs_book', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('crs_id'),
    sa.UniqueConstraint('crs_code'),
    sa.UniqueConstraint('crs_title')
    )
    op.create_table('student',
    sa.Column('std_id', sa.Integer(), nullable=False),
    sa.Column('std_regno', sa.Integer(), nullable=False),
    sa.Column('std_fname', sa.String(length=20), nullable=False),
    sa.Column('std_lname', sa.String(length=20), nullable=False),
    sa.Column('std_email', sa.String(length=30), nullable=False),
    sa.Column('std_dob', sa.String(length=10), nullable=False),
    sa.Column('std_gender', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('std_id'),
    sa.UniqueConstraint('std_email'),
    sa.UniqueConstraint('std_regno')
    )
    op.create_table('classroom',
    sa.Column('cls_id', sa.Integer(), nullable=False),
    sa.Column('cls_code', sa.String(length=20), nullable=False),
    sa.Column('cls_size', sa.String(length=50), nullable=False),
    sa.Column('cls_crs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cls_crs_id'], ['course.crs_id'], ),
    sa.PrimaryKeyConstraint('cls_id'),
    sa.UniqueConstraint('cls_code'),
    sa.UniqueConstraint('cls_size')
    )
    op.create_table('enrollments',
    sa.Column('se_crs_id', sa.Integer(), nullable=False),
    sa.Column('se_std_id', sa.Integer(), nullable=False),
    sa.Column('se_date', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['se_crs_id'], ['course.crs_id'], ),
    sa.ForeignKeyConstraint(['se_std_id'], ['student.std_id'], ),
    sa.PrimaryKeyConstraint('se_crs_id', 'se_std_id')
    )
    op.create_table('lecturer',
    sa.Column('lec_id', sa.Integer(), nullable=False),
    sa.Column('lec_title', sa.Integer(), nullable=False),
    sa.Column('lec_fname', sa.String(length=20), nullable=False),
    sa.Column('lec_lname', sa.String(length=20), nullable=False),
    sa.Column('lec_email', sa.String(length=30), nullable=False),
    sa.Column('lec_dob', sa.String(length=10), nullable=False),
    sa.Column('lec_gender', sa.String(length=10), nullable=False),
    sa.Column('lec_crs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lec_crs_id'], ['course.crs_id'], ),
    sa.PrimaryKeyConstraint('lec_id'),
    sa.UniqueConstraint('lec_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturer')
    op.drop_table('enrollments')
    op.drop_table('classroom')
    op.drop_table('student')
    op.drop_table('course')
    # ### end Alembic commands ###
