"""empty message

Revision ID: eb31d16a6dd1
Revises: 4ea76b5507aa
Create Date: 2021-08-08 20:23:48.794091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb31d16a6dd1'
down_revision = '4ea76b5507aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column(
        'se_semester', sa.String(length=30), nullable=False))
    op.drop_constraint('enrollments_pkey', 'enrollments', type_='primary')
    op.create_primary_key('enrollments_pkey', 'enrollments', [
                          'se_std_id', 'se_crs_id', 'se_semester'])
    op.drop_column('enrollments', 'se_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('se_date', sa.VARCHAR(
        length=30), autoincrement=False, nullable=True))
    op.drop_column('enrollments', 'se_semester')
    # ### end Alembic commands ###
